"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),crypto=require("node:crypto"),{EventEmitter}=require("node:events");
const {privateIP,resolvePublic}=require("../lib/network");const {createChannels,slackValid,whatsappValid,teamsValid}=require("../lib/channels");const {imapList,decodeMimeWord,sexpr}=require("../lib/imap");
test("渠道仅接本人私聊，拒绝群聊/他人、去重且换绑后不回传旧目标",async t=>{
  const fs=require("node:fs"),os=require("node:os"),path=require("node:path");const dir=fs.mkdtempSync(path.join(os.tmpdir(),"lumi-channel-"));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const jobs=[],channels=createChannels({dir,receive:b=>{jobs.push(b);return b;}});channels.configure({id:"slack",enabled:true,owner:"owner",token:"fixture",signingSecret:"secret"});
  async function slack(event,id){const raw=Buffer.from(JSON.stringify({event,event_id:id})),ts=String(Math.floor(Date.now()/1000)),headers={"x-slack-request-timestamp":ts,"x-slack-signature":"v0="+crypto.createHmac("sha256","secret").update("v0:"+ts+":").update(raw).digest("hex")};let status;const res={writeHead:s=>{status=s;},end:()=>{}};await channels.incoming("slack",{method:"POST",headers},res,new URL("https://fixture.example"),raw);assert.equal(status,200);}
  const message={type:"message",channel_type:"im",user:"owner",channel:"D123",text:"test"};
  await slack({...message,user:"another"},"other");await slack({...message,channel_type:"channel"},"group");assert.equal(jobs.length,0);
  await slack(message,"valid");await slack(message,"valid");assert.equal(jobs.length,1);assert.equal(jobs[0].channel,"slack");assert.equal(JSON.parse(jobs[0].channelTarget).owner,"owner");
  channels.configure({id:"slack",owner:"new-owner"});await assert.rejects(channels.reply({kind:"done"},{...jobs[0],result:"private"}),/禁止回传/);
});
test("私网、映射IPv6和特殊地址不可访问",async()=>{for(const ip of ["127.0.0.1","10.0.0.1","100.64.0.1","192.168.1.2","::1","::ffff:127.0.0.1","fc00::1","2001:db8::1"])assert.equal(privateIP(ip),true,ip);assert.equal(privateIP("8.8.8.8"),false);await assert.rejects(resolvePublic("http://127.1/"));await assert.rejects(resolvePublic("http://2130706433/"));await assert.rejects(resolvePublic("https://example.com:8080/"));});
test("Slack原始字节签名、时间窗和WhatsApp签名",()=>{const raw=Buffer.from('{"text":"中文"}'),secret="secret",ts=String(Math.floor(Date.now()/1000));const h={"x-slack-request-timestamp":ts,"x-slack-signature":"v0="+crypto.createHmac("sha256",secret).update("v0:"+ts+":").update(raw).digest("hex")};assert.equal(slackValid(secret,raw,h),true);assert.equal(slackValid(secret,Buffer.from("changed"),h),false);assert.equal(slackValid(secret,raw,h,Date.now()+600000),false);const wa={"x-hub-signature-256":"sha256="+crypto.createHmac("sha256",secret).update(raw).digest("hex")};assert.equal(whatsappValid(secret,raw,wa),true);assert.equal(whatsappValid("wrong",raw,wa),false);});
test("Teams校验JWT签名、本人渠道背书、服务URL与audience",async()=>{const {privateKey,publicKey}=crypto.generateKeyPairSync("rsa",{modulusLength:2048});const now=Math.floor(Date.now()/1000),activity={serviceUrl:"https://smba.trafficmanager.net/teams/",channelId:"msteams"};const key={...publicKey.export({format:"jwk"}),kid:"test",endorsements:["msteams"]};const fetcher=async()=>({ok:true,json:async()=>({keys:[key]})});function token(aud="app"){const h=Buffer.from(JSON.stringify({alg:"RS256",kid:"test"})).toString("base64url"),p=Buffer.from(JSON.stringify({iss:"https://api.botframework.com",aud,exp:now+3600,nbf:now-10,serviceurl:activity.serviceUrl})).toString("base64url");return h+"."+p+"."+crypto.sign("RSA-SHA256",Buffer.from(h+"."+p),privateKey).toString("base64url");}assert.equal(await teamsValid({appId:"app"},token(),activity,fetcher),true);assert.equal(await teamsValid({appId:"app"},token("other"),activity,fetcher),false);assert.equal(await teamsValid({appId:"app"},token(),{...activity,serviceUrl:"http://127.0.0.1/"},fetcher),false);});
function fakeImap(empty=false){const s=new EventEmitter();s.destroy=()=>{};s.write=cmd=>{const tag=cmd.split(" ")[0];let response;if(cmd.includes("LOGIN"))response=tag+" OK login\r\n";else if(cmd.includes("SELECT"))response="* "+(empty?0:1)+" EXISTS\r\n"+tag+" OK select\r\n";else if(cmd.includes("SEARCH"))response="* SEARCH 1\r\n"+tag+" OK search\r\n";else if(cmd.includes("FETCH")){const subject="中文";const literal=Buffer.from(subject).toString("latin1");response='* 1 FETCH (UID 77 FLAGS (\\Seen) ENVELOPE ("today" {'+Buffer.byteLength(subject)+'}\r\n'+literal+' (("Alice" NIL "a" "example.com")) NIL NIL NIL NIL NIL NIL NIL))\r\n'+tag+' OK fetch\r\n';}else return;const b=Buffer.from(response,"latin1");for(let i=0;i<b.length;i+=3)setImmediate(()=>s.emit("data",b.subarray(i,i+3)));};setImmediate(()=>s.emit("data",Buffer.from("* OK ready\r\n")));return s;}
test("IMAP逐3字节切包、literal、空邮箱、未读搜索和MIME解码",async()=>{for(const empty of [false,true]){const r=await imapList({host:"smtp.qq.com",user:"u",pass:"p"},{unreadOnly:true},()=>fakeImap(empty));assert.equal(r.list.length,empty?0:1);if(!empty){assert.equal(r.list[0].subject,"中文");assert.equal(r.list[0].id,"77");}}assert.equal(decodeMimeWord("=?UTF-8?B?5Lit5paH?="),"中文");assert.deepEqual(sexpr('(NIL "a\\\"b")'),[null,'a"b']);});
